services:
  pgdatabase:
    image: postgres:13
    user: "${UID}:${GID}"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    env_file:
      - .env
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    user: "${UID}:${GID}"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.come
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - "./data_pgadmin:/var/lib/pgadmin:rw"
    env_file:
      - .env
    ports:
      - "8080:80"